CREATE TABLE TBL_REGIONS
(
    REGION_ID integer PRIMARY KEY NOT NULL,
    X double NOT NULL,
    Y double NOT NULL,
    WIDTH integer NOT NULL,
    LENGTH integer NOT NULL,
    TYPE integer NOT NULL,
    HEIGHT integer,
    OXYGEN double,
    CARBONMONOXIDE double,
    METHANE double,
    TEMPERATURE double,
    HUMIDITY double
);
CREATE TABLE TBL_READERS
(
    RN_ID integer PRIMARY KEY NOT NULL,
    X double NOT NULL,
    Y double NOT NULL,
    RANGE integer NOT NULL,
    SUBREGION_ID integer NOT NULL,
    TYPE integer NOT NULL,
    BATTERY integer NOT NULL,
    BACKUP_BATTERY integer NOT NULL,
    CONSTRAINT TBL_READERS_REGION_FK FOREIGN KEY (SUBREGION_ID) REFERENCES TBL_REGIONS (REGION_ID)
);
CREATE INDEX TBL_READERS_TYPE_INDEX ON TBL_READERS (TYPE DESC);
CREATE TABLE TBL_ASSETS
(
    ASSET_ID integer PRIMARY KEY NOT NULL,
    TAG_ID integer NOT NULL,
    TYPE integer NOT NULL,
    STATUS varchar(10) NOT NULL,
    ERR_CODE integer NOT NULL,
    ASSIGNED_REGION integer,
    REGION integer,
    CONSTRAINT TBL_ASSETS_REGION_FK FOREIGN KEY (REGION) REFERENCES TBL_REGIONS (REGION_ID),
);
CREATE TABLE TBL_EMPLOYEES
(
    TAG_ID integer NOT NULL,
    EMPLOYEE_ID integer PRIMARY KEY NOT NULL,
    AUTH_LEVEL integer NOT NULL,
    REGION integer,
    ROLE integer,
    PANIC boolean,
    MOTION_ALARM boolean,
    CONSTRAINT TBL_EMPLOYEES_REGION_FK FOREIGN KEY (REGION) REFERENCES TBL_REGIONS (REGION_ID),
);
CREATE INDEX TBL_EMPLOYEES_ROLE_INDEX ON TBL_EMPLOYEES (ROLE);

CREATE TABLE TBL_VEHICLES
(
    VEHICLE_ID integer PRIMARY KEY NOT NULL,
    WIDTH integer NOT NULL,
    HEIGHT integer NOT NULL,
    TYPE integer NOT NULL,
    TAG_ID integer NOT NULL,
    REGION integer,
    CONSTRAINT TBL_VEHICLES_REGION_FK FOREIGN KEY (REGION) REFERENCES TBL_REGIONS (REGION_ID),
);


CREATE TABLE TBL_DANGERS
(
    REGION integer,
    TYPE integer,
    CONSTRAINT TBL_DANGERS_REGION_FK FOREIGN KEY (REGION) REFERENCES TBL_REGIONS (REGION_ID),
    PRIMARY KEY(REGION, TYPE)

)