(define 
  (problem iot)
  (:domain iot)
  (:objects dbell flt room speaker television Bob Jane John e1 playAudio displayMessage)
  (:init
    (Baby Jane) (Baby John)
    (Asleep John) (Awake Jane)
    (Doorbell dbell) (DoorbellEvent e1) (producedBy e1 dbell)
    (Flat flt) (inFlat John flt) (inFlat Jane flt) 
    (Adult Bob) (hasResident flt Bob) (inFlat Bob flt)
    (SoundNotification playAudio) (VisualAction displayMessage)
    (canPerform speaker playAudio) (canPerform television playAudio)
    (canPerform television displayMessage)
    (inFlat speaker flt) (inFlat television flt) (inRoom television room)
    (= (sleeping-baby speaker) 10) (= (sleeping-baby television) 10)
    (= (sleeping-baby dbell) 10)
    (= (total-cost) 0))
  (:goal (gotNotifiedFor Bob e1))
  (:metric minimize (total-cost))
  )