DROP TABLE IF EXISTS DEVICES;
DROP TABLE IF EXISTS PEOPLE;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS NOTIFICATIONS;

CREATE TABLE DEVICES(ID INT PRIMARY KEY AUTO_INCREMENT, Type INTEGER NOT NULL, Description VARCHAR(255));
CREATE TABLE PEOPLE(ID INT PRIMARY KEY AUTO_INCREMENT, Age INTEGER NOT NULL, Name VARCHAR(255));
CREATE TABLE EVENTS(ID INT PRIMARY KEY AUTO_INCREMENT, DeviceID INT, Type INTEGER NOT NULL, Description VARCHAR(255), FOREIGN KEY (DeviceID) REFERENCES Devices(ID));
CREATE TABLE NOTIFICATIONS(ID INT PRIMARY KEY AUTO_INCREMENT, Type INTEGER NOT NULL, PersonID INTEGER NOT NULL, ACTIVE BOOLEAN, FOREIGN KEY (PersonID) REFERENCES People(ID));

INSERT INTO DEVICES (TYPE, DESCRIPTION) VALUES (1, 'Flat Doorbell');
INSERT INTO PEOPLE (AGE, NAME) VALUES (32, 'BOB');
INSERT INTO PEOPLE (AGE, NAME) VALUES (1, 'JOHN');
INSERT INTO NOTIFICATIONS(TYPE, PERSONID, ACTIVE) VALUES (1, 1, FALSE);
INSERT INTO EVENTS(DEVICEID, TYPE, DESCRIPTION) VALUES (1, 1, 'There is someone at the front door!!');